# Generated by Django 6.0.3 on 2026-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('link_git', models.URLField()),
                ('link_linkedin', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
