# Generated by Django 6.0.3 on 2026-06-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pessoa_options_pessoa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='link_git',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='link_linkedin',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='url',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='git',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='linked',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='url_imagem',
            field=models.URLField(blank=True),
        ),
    ]
